name: CS102 Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==24.8.0 pytest==8.3.3 pandas==2.2.2
    - name: Run unittests
      run: |
        cd homework01
        python -m unittest discover ${{ github.head_ref }}
